on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: "ubuntu-latest-m"
    concurrency:  
      cancel-in-progress: false
      group: "main-push"      
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: composable
          skipAddingSubstituter: false
          skipPush: false
      - run: 
          nix run .#terraform --impure -- init
          nix run .#terraform --impure -- apply --auto-approve
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          rolling: true   